### PR TITLE
fix: added error checks on account routes

### LINKED ISSUE #211: Blank screens for "Secrets" and "Users", even on hemmelig.app
### Description

Under [Account], I find the following issues (while self-hosted _and_ on https://hemmelig.app):
1. The [Account] pane just shows a spinner, nothing else.
    > GET https://hemmelig.app/api/account/                [HTTP/2 401 Unauthorized 64ms]
2. Clicking on [Secrets] results in a completely blank page:
    > TypeError: x.map is not a function
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > eS https://hemmelig.app/assets/index-12b7880e.js:41
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26

    and

    > Uncaught (in promise) TypeError: x.map is not a function
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > St https://hemmelig.app/assets/secrets-19f81e3c.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > eS https://hemmelig.app/assets/index-12b7880e.js:41
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > [index-12b7880e.js:39:73](https://hemmelig.app/assets/index-12b7880e.js)
3. Clicking on [Users] results in a completely blank page:
    > TypeError: r.map is not a function
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > EventHandlerNonNull* https://hemmelig.app/assets/index-12b7880e.js:26
    > <anonymous> https://hemmelig.app/assets/index-12b7880e.js:26

    and

    > Uncaught (in promise) TypeError: r.map is not a function
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Jc https://hemmelig.app/assets/index-12b7880e.js:37
    > Nu https://hemmelig.app/assets/index-12b7880e.js:37
    > Sv https://hemmelig.app/assets/index-12b7880e.js:41
    > yv https://hemmelig.app/assets/index-12b7880e.js:41
    > Q_ https://hemmelig.app/assets/index-12b7880e.js:41
    > yo https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > At https://hemmelig.app/assets/index-12b7880e.js:37
    > hr https://hemmelig.app/assets/index-12b7880e.js:39
    > tf https://hemmelig.app/assets/index-12b7880e.js:37
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > Ue https://hemmelig.app/assets/users-f18f59f2.js:1
    > rS https://hemmelig.app/assets/index-12b7880e.js:41
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > $r https://hemmelig.app/assets/index-12b7880e.js:41
    > Vu https://hemmelig.app/assets/index-12b7880e.js:39
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > unstable_runWithPriority https://hemmelig.app/assets/index-12b7880e.js:26
    > Hr https://hemmelig.app/assets/index-12b7880e.js:37
    > H0 https://hemmelig.app/assets/index-12b7880e.js:37
    > Y https://hemmelig.app/assets/index-12b7880e.js:26
    > onmessage https://hemmelig.app/assets/index-12b7880e.js:26
    > EventHandlerNonNull* https://hemmelig.app/assets/index-12b7880e.js:26
    > <anonymous> https://hemmelig.app/assets/index-12b7880e.js:26

Additionally, the browser console is riddled with these issues:
> Unexpected value 3.625rem parsing width attribute.                [index-12b7880e.js:33:5143](https://hemmelig.app/assets/index-12b7880e.js)

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by m4-droid**
fixes #211 
: added loader on every route like /account
: added success notification on some routes
: added specific notification message upon deletion success
: added extra checks for routes
: added more descriptive variable names
: added redirect to /signout upon account deletion
: added general timeout of 2.5s on success notification
: other fixes
-- : error: isLoggedIn: true was dispatched due to delay in clearing cookie & calling getCookie() in useEffect() of Header
-- : fix: added await for async call of signOut() in useEffect() of SignOut component

### CODE REVIEW

**Comment by m4-droid** [comment]
I am not sure error mentioned in other fixes is general or specific to me (used chrome browser).

**Comment by m4-droid** [comment]
I am working on this code duplication issue in SonarCloud Quality Gate test.
If anything else is concerning in code or any suggestion related to reducing code duplication or adding something in code, let me know.

**Comment by bjarneo** [comment]
Thank you. I will look into this PR as soon as I have some spare time :)

**Comment by m4-droid** [comment]
It would be great if you could review this before Hacktoberfest ends.

**Comment by m4-droid** [comment]
It would be great if you could review this before Hacktoberfest ends.

**Review by bjarneo — APPROVED** [review]
Really great PR! Thank you for this cleanup :) 

We have to remove the prevalidation for the :id/burn route as everyone should be able to burn their secret. I will just commit that directly to the main branch.

**Pull request merged**
