### PR TITLE
Add Dutch locale

### PR DESCRIPTION
**Pull request by ltguillaume**

### CODE REVIEW

**Comment by ltguillaume** [comment]
I saw that some back-end stuff is not yet translatable.

**Comment by bjarneo** [comment]
> I saw that some back-end stuff is not yet translatable.

Yes, that is true. I think several things in the frontend hasn't been updated to be translated either.

Thanks for this PR :)

**Comment by ltguillaume** [comment]
@bjarneo I just updated the docker image, double-checked that the Dutch locale was present in the image, then fired up the browser: the interface sticks to English somehow. Tested in Chromium and LibreWolf.

**Comment by bjarneo** [comment]
@ltguillaume if I remember correctly, you have to set this to `nl`: SECRET_FORCED_LANGUAGE

The logic is here: https://github.com/HemmeligOrg/Hemmelig.app/blob/bd17097e57b23af88c8f3c08f14a40dde0f22951/src/i18n.js#L8C1-L8C1

**Comment by ltguillaume** [comment]
Doesn't work either. I also tried to set `SECRET_FORCED_LANGUAGE=de` for German. No go.

**Comment by bjarneo** [comment]
> @bjarneo I just updated the docker image, double-checked that the Dutch locale was present in the image, then fired up the browser: the interface sticks to English somehow. Tested in Chromium and LibreWolf.
> 
> `SECRET_FORCED_LANGUAGE=nl` doesn't do the trick either.

Hm, then we have a bug, for sure. The SECRETD_FORCED_LANGUAGE should have done the trick. I mean

https://github.com/HemmeligOrg/Hemmelig.app/blob/bd17097e57b23af88c8f3c08f14a40dde0f22951/src/i18n.js#L8C1-L21
this logic sets the fallback language.

I will have a look at it. I do not have time today though.

**Pull request merged**
